name: fitnessapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.2
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dropdown_button2: ^1.9.4
 
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_database: ^11.3.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.7.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_blue_plus: ^1.35.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.1
  googleapis: ^13.0.0
  health: ^9.0.0
  http: ^1.3.0
  hidden_drawer_menu: ^3.0.1
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^3.3.1
  mockito: ^5.4.0
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.0
  slide_to_act: ^2.0.1
  smooth_page_indicator: ^1.0.1
  timezone: ^0.10.0
 

 
dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.2

  
  

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
